# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1000, 706)
        self.backLabel = QtWidgets.QLabel(widget)
        self.backLabel.setGeometry(QtCore.QRect(0, 0, 1000, 706))
        self.backLabel.setText("")
        self.backLabel.setPixmap(QtGui.QPixmap("back.jpg"))
        self.backLabel.setObjectName("backLabel")
        self.cameraLabel = QtWidgets.QLabel(widget)
        self.cameraLabel.setGeometry(QtCore.QRect(110, 150, 401, 431))
        self.cameraLabel.setText("")
        self.cameraLabel.setObjectName("cameraLabel")
        self.titlelabel = QtWidgets.QLabel(widget)
        self.titlelabel.setGeometry(QtCore.QRect(320, 0, 351, 70))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.titlelabel.setFont(font)
        self.titlelabel.setStyleSheet("color: rgb(0, 183, 191);")
        self.titlelabel.setObjectName("titlelabel")
        self.timeLabel = QtWidgets.QLabel(widget)
        self.timeLabel.setGeometry(QtCore.QRect(590, 130, 311, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.timeLabel.setFont(font)
        self.timeLabel.setStyleSheet("color: rgb(0, 183, 191);")
        self.timeLabel.setObjectName("timeLabel")
        self.dateLabel = QtWidgets.QLabel(widget)
        self.dateLabel.setGeometry(QtCore.QRect(750, 0, 241, 70))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.dateLabel.setFont(font)
        self.dateLabel.setStyleSheet("color: rgb(0, 183, 191);")
        self.dateLabel.setObjectName("dateLabel")
        self.InputEdit = QtWidgets.QLineEdit(widget)
        self.InputEdit.setGeometry(QtCore.QRect(600, 240, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.InputEdit.setFont(font)
        self.InputEdit.setStyleSheet("color: rgb(0, 183, 191);\n"
"background-color: rgb(38, 69, 64);")
        self.InputEdit.setText("")
        self.InputEdit.setObjectName("InputEdit")
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(790, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(38, 69, 64);\n"
"color: rgb(0, 183, 191);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(widget)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(38, 69, 64);\n"
"color: rgb(0, 183, 191);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(widget)
        self.pushButton_3.setGeometry(QtCore.QRect(790, 310, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color: rgb(38, 69, 64);\n"
"color: rgb(0, 183, 191);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(widget)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 600, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(38, 69, 64);\n"
"color: rgb(0, 183, 191);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.textBrowser = QtWidgets.QTextBrowser(widget)
        self.textBrowser.setGeometry(QtCore.QRect(600, 380, 291, 211))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 69, 84);")
        self.textBrowser.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textBrowser.setObjectName("textBrowser")
        self.iconLabel = QtWidgets.QLabel(widget)
        self.iconLabel.setGeometry(QtCore.QRect(0, 0, 121, 70))
        self.iconLabel.setText("")
        self.iconLabel.setPixmap(QtGui.QPixmap("icon1.jpg"))
        self.iconLabel.setObjectName("iconLabel")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "人脸采集识别系统"))
        self.titlelabel.setText(_translate("widget", "人脸采集识别终端"))
        self.timeLabel.setText(_translate("widget", "TextLabel"))
        self.dateLabel.setText(_translate("widget", "TextLabel"))
        self.InputEdit.setPlaceholderText(_translate("widget", "请输入您的名字"))
        self.pushButton.setText(_translate("widget", "开始检测"))
        self.pushButton_2.setText(_translate("widget", "开始训练"))
        self.pushButton_3.setText(_translate("widget", "开始识别"))
        self.pushButton_4.setText(_translate("widget", "退出系统"))
        self.textBrowser.setHtml(_translate("widget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">使用说明：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1.请靠近摄像头开始检测采集人脸</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2.开始训练生成识别模型</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3.请靠近摄像头开始识别人脸</p></body></html>"))
